### ISSUE TITLE
False negative for method calls involving inlinable selector expressions

### ISSUE THREAD

**Issue by dominikh** [jordanlewis/gcassert#5]
Input:

```
package pkg

func foo() {
	Gen().Layout()
}

func Gen() S {
	return S{}
}

//gcassert:inline
func (s S) Layout() {
	select {}
}

type S struct{}
```

`go build -gcflags=-m`:

```
$ go build -gcflags=-m foo.go
# command-line-arguments
./foo.go:7:6: can inline Gen
./foo.go:3:6: can inline foo
./foo.go:4:5: inlining call to Gen
```

Output of gcassert@latest:

None.

This works fine for `var s S; s.Layout()`. This also works fine if `Gen` cannot be inlined.

**Comment by jordanlewis** [comment]
Thanks for filing, the tool doesn't understand how to deal with multiple callsites on a single line - it coalesces them into one. Will send a fix.

**Comment by jordanlewis** [comment]
Fixed in https://github.com/jordanlewis/gcassert/commit/f5bfb438338e11a577a05d6f83e5157821097fb6, please have another try

**Comment by dominikh** [comment]
Seems to work, thanks.
